[14:06:20]:[PbxBot]:[INFO] - ••• Starting PBX 2.0 Client & User •••
[14:06:25]:[PbxBot]:[INFO] - ↠↠ Started PbxBot Client: 'Pbx055Bot' ↞↞
[14:06:27]:[PbxBot]:[INFO] - ••• Loaded User Plugin: '71' •••
[14:06:27]:[PbxBot]:[INFO] - ••• Database Connection Established! •••
[14:06:27]:[PbxBot]:[INFO] - ••• Setting Up Users •••
[14:06:27]:[PbxBot]:[INFO] - ↠↠ Added Authorized Users ↞↞
[14:06:27]:[PbxBot]:[INFO] - ↠↠ Added Stan Users ↞↞
[14:06:27]:[PbxBot]:[INFO] - ↠↠ Added 1 Gbanned Users ↞↞
[14:06:27]:[PbxBot]:[INFO] - ↠↠ Added 0 Gmuted Users ↞↞
[14:08:02]:[PbxBot]:[INFO] - ••• Starting PBX 2.0 Client & User •••
[14:08:02]:[PbxBot]:[INFO] - ↠↠ Started PbxBot Client: 'Pbx055Bot' ↞↞
[14:08:03]:[PbxBot]:[INFO] - ↠↠ Started User 1: '❤️' ↞↞
[14:08:05]:[PbxBot]:[INFO] - ••• Loaded User Plugin: '71' •••
[14:08:05]:[PbxBot]:[INFO] - ••• Database Connection Established! •••
[14:08:05]:[PbxBot]:[INFO] - ••• Setting Up Users •••
[14:08:05]:[PbxBot]:[INFO] - ↠↠ Added Authorized Users ↞↞
[14:08:05]:[PbxBot]:[INFO] - ↠↠ Added Stan Users ↞↞
[14:08:05]:[PbxBot]:[INFO] - ↠↠ Added 1 Gbanned Users ↞↞
[14:08:05]:[PbxBot]:[INFO] - ↠↠ Added 0 Gmuted Users ↞↞
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[03:30:41]:[pyrogram.dispatcher]:[ERROR] - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 143, in check
    listener = client.listening.get(update.chat.id)
AttributeError: 'NoneType' object has no attribute 'id'
[12:13:37]:[pyrogram.dispatcher]:[ERROR] - Telegram says: [403 MESSAGE_AUTHOR_REQUIRED] - You are not the author of this message (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyroaddon/listen/listen.py", line 139, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/home/ubuntu/Pbxbot/Pbxbot/plugins/decorator.py", line 59, in wrapper
    await func(client, message)
  File "/home/ubuntu/Pbxbot/Pbxbot/plugins/user/badword.py", line 56, in i_am_not_allowed_to_say_this
    await message.edit(txt)
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/types/messages_and_media/message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.forbidden_403.MessageAuthorRequired: Telegram says: [403 MESSAGE_AUTHOR_REQUIRED] - You are not the author of this message (caused by "messages.EditMessage")
[14:35:47]:[asyncio]:[ERROR] - Task exception was never retrieved
future: <Task finished name='Task-297647' coro=<Session.restart() done, defined at /home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py:182> exception=AuthKeyDuplicated('Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")')>
Traceback (most recent call last):
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 184, in restart
    await self.start()
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 144, in start
    raise e
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 120, in start
    await self.send(
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/Pbxbot/venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")
